// genwordlist generates a Scrabble-compatible word list.
// It downloads the Collins Scrabble Words list from a public source.
package main

import (
	"bufio"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"unicode"
)

func main() {
	// Use the enable word list (public domain, ~173k words, commonly used for Scrabble)
	url := "https://raw.githubusercontent.com/benhoyt/boggle/master/word-list.txt"

	fmt.Println("Downloading word list...")
	resp, err := http.Get(url)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Download failed: %v\nGenerating basic word list instead.\n", err)
		generateBasicList()
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		fmt.Fprintf(os.Stderr, "Download returned %d. Generating basic word list instead.\n", resp.StatusCode)
		generateBasicList()
		return
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Read failed: %v\nGenerating basic word list instead.\n", err)
		generateBasicList()
		return
	}

	f, err := os.Create("data/words.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Create file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	count := 0
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		word := strings.TrimSpace(scanner.Text())
		word = strings.ToUpper(word)
		if isValidScrabbleWord(word) {
			fmt.Fprintln(w, word)
			count++
		}
	}
	w.Flush()
	fmt.Printf("Wrote %d words to data/words.txt\n", count)
}

func isValidScrabbleWord(word string) bool {
	if len(word) < 2 || len(word) > 15 {
		return false
	}
	for _, r := range word {
		if !unicode.IsUpper(r) {
			return false
		}
	}
	return true
}

func generateBasicList() {
	// Generate a basic English word list for Scrabble
	// This is a fallback with common 2-7 letter words
	words := getBasicWords()

	f, err := os.Create("data/words.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Create file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	for _, word := range words {
		fmt.Fprintln(w, word)
	}
	w.Flush()
	fmt.Printf("Wrote %d basic words to data/words.txt\n", len(words))
}

func getBasicWords() []string {
	return []string{
		// 2-letter words (all valid Scrabble 2-letter words)
		"AA", "AB", "AD", "AE", "AG", "AH", "AI", "AL", "AM", "AN", "AR", "AS", "AT", "AW", "AX", "AY",
		"BA", "BE", "BI", "BO", "BY",
		"DA", "DE", "DO",
		"ED", "EF", "EH", "EL", "EM", "EN", "ER", "ES", "ET", "EW", "EX",
		"FA", "FE",
		"GI", "GO",
		"HA", "HE", "HI", "HM", "HO",
		"ID", "IF", "IN", "IS", "IT",
		"JO",
		"KA", "KI",
		"LA", "LI", "LO",
		"MA", "ME", "MI", "MM", "MO", "MU", "MY",
		"NA", "NE", "NO", "NU",
		"OD", "OE", "OF", "OH", "OI", "OK", "OM", "ON", "OO", "OP", "OR", "OS", "OU", "OW", "OX", "OY",
		"PA", "PE", "PI", "PO",
		"QI",
		"RE",
		"SH", "SI", "SO",
		"TA", "TI", "TO",
		"UH", "UM", "UN", "UP", "US", "UT",
		"WE", "WO",
		"XI", "XU",
		"YA", "YE", "YO",
		"ZA", "ZO",
		// Common 3+ letter words
		"THE", "AND", "FOR", "ARE", "BUT", "NOT", "YOU", "ALL", "CAN", "HER", "WAS", "ONE", "OUR", "OUT",
		"ACE", "ACT", "ADD", "AGE", "AGO", "AID", "AIM", "AIR", "ALE", "ALL", "AND", "ANT", "ANY", "APE",
		"ARC", "ARE", "ARK", "ARM", "ART", "ASH", "ASK", "ATE", "AWE", "AXE",
		"BAD", "BAG", "BAN", "BAR", "BAT", "BAY", "BED", "BET", "BIG", "BIT", "BOW", "BOX", "BOY", "BUD",
		"BUG", "BUN", "BUS", "BUT", "BUY",
		"CAB", "CAN", "CAP", "CAR", "CAT", "COP", "COT", "COW", "CRY", "CUB", "CUP", "CUR", "CUT",
		"DAB", "DAD", "DAM", "DAY", "DEN", "DEW", "DID", "DIG", "DIM", "DIP", "DOC", "DOE", "DOG", "DOT", "DRY", "DUB", "DUD", "DUE", "DUG", "DUN", "DUO",
		"EAR", "EAT", "EEL", "EGG", "ELF", "ELK", "ELM", "EMU", "END", "ERA", "EVE", "EWE", "EYE",
		"FAN", "FAR", "FAT", "FAX", "FED", "FEW", "FIG", "FIN", "FIT", "FIX", "FLY", "FOB", "FOG", "FOP", "FOR", "FOX", "FRY", "FUN", "FUR",
		"GAB", "GAG", "GAP", "GAS", "GAY", "GEL", "GEM", "GET", "GIG", "GIN", "GNU", "GOB", "GOD", "GOT", "GUM", "GUN", "GUT", "GUY", "GYM",
		"HAD", "HAM", "HAS", "HAT", "HAY", "HEN", "HER", "HEW", "HID", "HIM", "HIP", "HIS", "HIT", "HOB", "HOG", "HOP", "HOT", "HOW", "HUB", "HUE", "HUG", "HUM", "HUT",
		"ICE", "ICY", "ILL", "IMP", "INK", "INN", "ION", "IRE", "IRK", "ITS", "IVY",
		"JAB", "JAG", "JAM", "JAR", "JAW", "JAY", "JET", "JIG", "JOB", "JOG", "JOT", "JOY", "JUG", "JUT",
		"KEG", "KEN", "KEY", "KID", "KIN", "KIT",
		"LAB", "LAD", "LAG", "LAP", "LAW", "LAY", "LED", "LEG", "LET", "LID", "LIE", "LIP", "LIT", "LOG", "LOT", "LOW",
		"MAD", "MAN", "MAP", "MAR", "MAT", "MAW", "MAX", "MAY", "MEN", "MET", "MID", "MIX", "MOB", "MOM", "MOP", "MOW", "MUD", "MUG", "MUM",
		"NAB", "NAG", "NAP", "NET", "NEW", "NIL", "NIT", "NOB", "NOD", "NOR", "NOT", "NOW", "NUB", "NUN", "NUT",
		"OAK", "OAR", "OAT", "ODD", "ODE", "OFF", "OFT", "OIL", "OLD", "ONE", "OPT", "ORB", "ORE", "OUR", "OUT", "OWE", "OWL", "OWN",
		"PAD", "PAL", "PAN", "PAP", "PAT", "PAW", "PAY", "PEA", "PEG", "PEN", "PEP", "PER", "PET", "PEW", "PIE", "PIG", "PIN", "PIT", "PLY", "POD", "POP", "POT", "POW", "PRY", "PUB", "PUG", "PUN", "PUP", "PUS", "PUT",
		"RAG", "RAM", "RAN", "RAP", "RAT", "RAW", "RAY", "RED", "REF", "RIB", "RID", "RIG", "RIM", "RIP", "ROB", "ROD", "ROT", "ROW", "RUB", "RUG", "RUM", "RUN", "RUT", "RYE",
		"SAC", "SAD", "SAG", "SAP", "SAT", "SAW", "SAY", "SEA", "SET", "SEW", "SHE", "SHY", "SIN", "SIP", "SIR", "SIS", "SIT", "SIX", "SKI", "SKY", "SLY", "SOB", "SOD", "SON", "SOP", "SOT", "SOW", "SOY", "SPA", "SPY", "STY", "SUB", "SUM", "SUN", "SUP",
		"TAB", "TAD", "TAG", "TAN", "TAP", "TAR", "TAT", "TAX", "TEA", "TEN", "THE", "THY", "TIE", "TIN", "TIP", "TOE", "TON", "TOO", "TOP", "TOT", "TOW", "TOY", "TUB", "TUG", "TUN", "TWO",
		"URN", "USE",
		"VAN", "VAT", "VET", "VIA", "VIE", "VOW",
		"WAD", "WAG", "WAR", "WAX", "WAY", "WEB", "WED", "WET", "WHO", "WHY", "WIG", "WIN", "WIT", "WOE", "WOK", "WON", "WOO", "WOW",
		"YAK", "YAM", "YAP", "YAW", "YEA", "YES", "YET", "YEW", "YIN", "YOU", "YOW",
		"ZAP", "ZED", "ZEN", "ZIP", "ZIT", "ZOO",
		// Common 4-letter words
		"ABLE", "ACHE", "ACID", "ACRE", "AGED", "AIDE", "ALLY", "ALSO", "ARCH", "AREA", "ARMY",
		"BACK", "BAKE", "BALD", "BALE", "BALL", "BAND", "BANE", "BANG", "BANK", "BARE", "BARK", "BARN", "BASE", "BATH", "BEAD", "BEAM", "BEAN", "BEAR", "BEAT", "BEEF", "BEEN", "BEER", "BELL", "BELT", "BEND", "BEST", "BIKE", "BILL", "BIND", "BIRD", "BITE", "BLOW", "BLUE", "BLUR", "BOAT", "BODY", "BOLD", "BOLT", "BOMB", "BOND", "BONE", "BOOK", "BOOM", "BOOT", "BORE", "BORN", "BOSS", "BOTH", "BOWL", "BULK", "BULL", "BUMP", "BURN", "BURY", "BUSH", "BUSY", "BUZZ",
		"CAFE", "CAGE", "CAKE", "CALL", "CALM", "CAME", "CAMP", "CAPE", "CARD", "CARE", "CART", "CASE", "CASH", "CAST", "CAVE", "CELL", "CHAT", "CHIP", "CHOP", "CITE", "CITY", "CLAD", "CLAM", "CLAP", "CLAY", "CLIP", "CLOCK", "CLUB", "CLUE", "COAL", "COAT", "CODE", "COIL", "COIN", "COLD", "COLE", "COME", "CONE", "COOK", "COOL", "COPE", "COPY", "CORD", "CORE", "CORK", "CORN", "COST", "COSY", "COUP", "COVE", "COZY", "CREW", "CROP", "CROW", "CUBE", "CULT", "CURE", "CURL", "CUTE",
		"DALE", "DAME", "DAMP", "DARE", "DARK", "DART", "DASH", "DATA", "DATE", "DAWN", "DEAD", "DEAF", "DEAL", "DEAR", "DEBT", "DECK", "DEED", "DEEM", "DEEP", "DEER", "DEMO", "DENY", "DESK", "DIAL", "DICE", "DIET", "DIRE", "DIRT", "DISK", "DOCK", "DOES", "DOME", "DONE", "DOOM", "DOOR", "DOSE", "DOTS", "DOWN", "DRAG", "DRAW", "DREW", "DROP", "DRUM", "DUAL", "DUEL", "DUKE", "DULL", "DUMB", "DUMP", "DUNE", "DUSK", "DUST", "DUTY",
		"EACH", "EARL", "EARN", "EASE", "EAST", "EASY", "ECHO", "EDGE", "EDIT", "ELSE", "EMIT", "EPIC", "EVEN", "EVER", "EVIL", "EXAM", "EXEC", "EXIT", "EYED", "EYES",
		"FACE", "FACT", "FADE", "FAIL", "FAIR", "FAKE", "FALL", "FAME", "FANG", "FARE", "FARM", "FAST", "FATE", "FAWN", "FEAR", "FEAT", "FEED", "FEEL", "FEET", "FELL", "FELT", "FILE", "FILL", "FILM", "FIND", "FINE", "FIRE", "FIRM", "FISH", "FIST", "FLAG", "FLAME", "FLAP", "FLAT", "FLAW", "FLED", "FLEW", "FLIP", "FLIT", "FLOCK", "FLOG", "FLOW", "FOAM", "FOIL", "FOLD", "FOLK", "FOND", "FONT", "FOOD", "FOOL", "FOOT", "FORD", "FORE", "FORK", "FORM", "FORT", "FOUL", "FOUR", "FREE", "FROM", "FUEL", "FULL", "FUND", "FURY", "FUSE", "FUSS",
		"GAIN", "GALE", "GAME", "GANG", "GAPE", "GARB", "GATE", "GAVE", "GAZE", "GEAR", "GENE", "GIFT", "GIRL", "GIVE", "GLAD", "GLEE", "GLEN", "GLOW", "GLUE", "GOAT", "GOES", "GOLD", "GOLF", "GONE", "GOOD", "GORE", "GRAB", "GRAY", "GREW", "GRID", "GRIM", "GRIN", "GRIP", "GRIT", "GROW", "GULF", "GURU",
		"HACK", "HAIL", "HAIR", "HALE", "HALF", "HALL", "HALT", "HAND", "HANG", "HARD", "HARE", "HARM", "HARP", "HATE", "HAUL", "HAVE", "HAZE", "HEAD", "HEAL", "HEAP", "HEAR", "HEAT", "HEED", "HEEL", "HELD", "HELL", "HELP", "HERB", "HERD", "HERE", "HERO", "HIGH", "HIKE", "HILL", "HILT", "HIND", "HINT", "HIRE", "HOLD", "HOLE", "HOLY", "HOME", "HOOD", "HOOK", "HOPE", "HORN", "HOST", "HOUR", "HOWL", "HUGE", "HULL", "HUNG", "HUNT", "HURT",
		"ICON", "IDEA", "IDLE", "INCH",
		"JACK", "JADE", "JAIL", "JANE", "JAWS", "JAZZ", "JEAN", "JEST", "JOBS", "JOIN", "JOKE", "JOLT", "JUMP", "JUNE", "JURY", "JUST",
		"KEEN", "KEEP", "KEPT", "KICK", "KIDS", "KILL", "KIND", "KING", "KISS", "KITE", "KNEE", "KNEW", "KNIT", "KNOB", "KNOT", "KNOW",
		"LACE", "LACK", "LAID", "LAKE", "LAMB", "LAME", "LAMP", "LAND", "LANE", "LARD", "LARK", "LASH", "LAST", "LATE", "LAWN", "LEAD", "LEAF", "LEAK", "LEAN", "LEAP", "LEFT", "LEND", "LENS", "LESS", "LIED", "LIFE", "LIFT", "LIKE", "LIMB", "LIME", "LIMP", "LINE", "LINK", "LION", "LIST", "LIVE", "LOAD", "LOAF", "LOAN", "LOCK", "LOFT", "LOGO", "LONE", "LONG", "LOOK", "LOOP", "LORD", "LORE", "LOSE", "LOSS", "LOST", "LOTS", "LOUD", "LOVE", "LUCK", "LUMP", "LURE", "LURK", "LUSH", "LUST",
		"MADE", "MAID", "MAIL", "MAIN", "MAKE", "MALE", "MALL", "MALT", "MANE", "MANY", "MARE", "MARK", "MASK", "MASS", "MAST", "MATE", "MAZE", "MEAL", "MEAN", "MEAT", "MEET", "MELT", "MEMO", "MEND", "MENU", "MERE", "MESH", "MESS", "MILD", "MILE", "MILK", "MILL", "MIME", "MIND", "MINE", "MINT", "MISS", "MODE", "MOLD", "MOLE", "MOOD", "MOON", "MOOR", "MORE", "MOSS", "MOST", "MOTH", "MOVE", "MUCH", "MULE", "MUSE", "MUST", "MUTE",
		"NAIL", "NAME", "NAVE", "NAVY", "NEAR", "NEAT", "NECK", "NEED", "NEST", "NEWS", "NEXT", "NICE", "NINE", "NODE", "NONE", "NOON", "NORM", "NOSE", "NOTE", "NOUN", "NUDE",
		"OATH", "OBEY", "ODDS", "OILS", "OKAY", "OMEN", "OMIT", "ONCE", "ONLY", "ONTO", "OPEN", "ORAL", "OVEN", "OVER", "OWED", "OWNS",
		"PACE", "PACK", "PAGE", "PAID", "PAIL", "PAIN", "PAIR", "PALE", "PALM", "PANE", "PARK", "PART", "PASS", "PAST", "PATH", "PAVE", "PAWN", "PEAK", "PEAR", "PEEL", "PEER", "PILE", "PINE", "PINK", "PIPE", "PITY", "PLAN", "PLAY", "PLEA", "PLOT", "PLOY", "PLUG", "PLUM", "PLUS", "POEM", "POET", "POLE", "POLL", "POLO", "POND", "PONY", "POOL", "POOR", "POPE", "PORK", "PORT", "POSE", "POST", "POUR", "PRAY", "PREY", "PROP", "PULL", "PULP", "PUMP", "PUNK", "PURE", "PUSH",
		"QUIT", "QUIZ",
		"RACE", "RACK", "RAFT", "RAGE", "RAID", "RAIL", "RAIN", "RAKE", "RAMP", "RANG", "RANK", "RARE", "RASH", "RATE", "RAVE", "READ", "REAL", "REAP", "REAR", "REEF", "REEL", "RELY", "REND", "RENT", "REST", "RICE", "RICH", "RIDE", "RIFT", "RILE", "RING", "RIOT", "RIPE", "RISE", "RISK", "ROAD", "ROAM", "ROAR", "ROBE", "ROCK", "RODE", "ROLE", "ROLL", "ROOF", "ROOM", "ROOT", "ROPE", "ROSE", "ROTE", "ROUT", "RUDE", "RUIN", "RULE", "RUNG", "RUSH", "RUST",
		"SACK", "SAFE", "SAGE", "SAID", "SAIL", "SAKE", "SALE", "SALT", "SAME", "SAND", "SANE", "SANG", "SANK", "SAVE", "SEAL", "SEAM", "SEAT", "SECT", "SEED", "SEEK", "SEEM", "SEEN", "SELF", "SELL", "SEND", "SENT", "SHED", "SHIN", "SHIP", "SHOE", "SHOP", "SHOT", "SHOW", "SHUT", "SICK", "SIDE", "SIFT", "SIGH", "SIGN", "SILK", "SILL", "SILO", "SILT", "SING", "SINK", "SITE", "SIZE", "SKIN", "SKIP", "SLAB", "SLAM", "SLAP", "SLAT", "SLAY", "SLED", "SLEW", "SLID", "SLIM", "SLIP", "SLIT", "SLOT", "SLOW", "SLUG", "SLUM", "SNAP", "SNIP", "SNOW", "SNUB", "SNUG", "SOAK", "SOAP", "SOAR", "SOCK", "SODA", "SOFA", "SOFT", "SOIL", "SOLD", "SOLE", "SOME", "SONG", "SOON", "SOOT", "SORE", "SORT", "SOUL", "SOUR", "SPAN", "SPAR", "SPEC", "SPED", "SPIN", "SPIT", "SPOT", "SPRY", "SPUR", "STAB", "STAR", "STAY", "STEM", "STEP", "STEW", "STIR", "STOP", "STOW", "STUB", "STUD", "STUN", "SUCH", "SUIT", "SULK", "SUNG", "SUNK", "SURE", "SURF", "SWAN", "SWAP", "SWAY", "SWIM",
		"TACK", "TACT", "TAIL", "TAKE", "TALE", "TALK", "TALL", "TAME", "TANK", "TAPE", "TART", "TASK", "TAXI", "TEAK", "TEAL", "TEAM", "TEAR", "TEEN", "TELL", "TEND", "TENT", "TERM", "TEST", "TEXT", "THAN", "THAT", "THEM", "THEN", "THEY", "THIN", "THIS", "TIDY", "TIED", "TIER", "TILE", "TILL", "TILT", "TIME", "TINY", "TIRE", "TOAD", "TOED", "TOIL", "TOLD", "TOLL", "TOMB", "TONE", "TOOK", "TOOL", "TOPS", "TORE", "TORN", "TOSS", "TOUR", "TOWN", "TRAP", "TRAY", "TREE", "TREK", "TRIM", "TRIO", "TRIP", "TROD", "TROT", "TRUE", "TUBE", "TUCK", "TUNA", "TUNE", "TURF", "TURN", "TWIN", "TYPE",
		"UGLY", "UNDO", "UNIT", "UNTO", "UPON", "URGE", "USED", "USER",
		"VAIN", "VALE", "VANE", "VARY", "VAST", "VEIL", "VEIN", "VENT", "VERB", "VERY", "VEST", "VETO", "VICE", "VIEW", "VINE", "VISA", "VOID", "VOLT", "VOTE",
		"WADE", "WAGE", "WAIT", "WAKE", "WALK", "WALL", "WAND", "WANT", "WARD", "WARM", "WARN", "WARP", "WART", "WARY", "WASH", "WASP", "WAVE", "WAVY", "WAXY", "WEAK", "WEAN", "WEAR", "WEED", "WEEK", "WEEP", "WELD", "WELL", "WENT", "WEPT", "WERE", "WEST", "WHAT", "WHEN", "WHIM", "WHIP", "WHOM", "WICK", "WIDE", "WIFE", "WILD", "WILL", "WILT", "WILY", "WIND", "WINE", "WING", "WINK", "WIPE", "WIRE", "WISE", "WISH", "WITH", "WOKE", "WOLF", "WOMB", "WOOD", "WOOL", "WORD", "WORE", "WORK", "WORM", "WORN", "WRAP", "WREN",
		"YARD", "YARN", "YEAR", "YELL", "YOUR",
		"ZEAL", "ZERO", "ZEST", "ZINC", "ZONE", "ZOOM",
		// Common 5-letter words
		"ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADMIT", "ADOPT", "ADULT", "AFTER", "AGAIN", "AGENT", "AGREE", "AHEAD", "ALARM", "ALBUM", "ALERT", "ALIEN", "ALIGN", "ALIKE", "ALIVE", "ALLEY", "ALLOW", "ALONE", "ALONG", "ALTER", "AMONG", "AMPLE", "ANGEL", "ANGER", "ANGLE", "ANGRY", "ANKLE", "ANNEX", "APART", "APPLE", "APPLY", "ARENA", "ARGUE", "ARISE", "ARMOR", "ARRAY", "ARROW", "ASIDE", "ASSET", "ATTIC", "AVOID", "AWARD", "AWARE",
		"BADGE", "BADLY", "BASIC", "BASIN", "BASIS", "BATCH", "BEACH", "BEARD", "BEAST", "BEGIN", "BEING", "BELOW", "BENCH", "BERRY", "BIRTH", "BLACK", "BLADE", "BLAME", "BLAND", "BLANK", "BLAST", "BLAZE", "BLEED", "BLEND", "BLESS", "BLIND", "BLISS", "BLOCK", "BLOND", "BLOOD", "BLOWN", "BLUES", "BLUFF", "BLUNT", "BLURT", "BOARD", "BOAST", "BONUS", "BOOTH", "BOUND", "BRAIN", "BRAND", "BRAVE", "BREAD", "BREAK", "BREED", "BRICK", "BRIDE", "BRIEF", "BRING", "BRISK", "BROAD", "BROKE", "BROOK", "BROWN", "BRUSH", "BUILD", "BUNCH", "BURST", "BUYER",
		"CABIN", "CABLE", "CAMEL", "CANDY", "CARGO", "CARRY", "CATCH", "CAUSE", "CEASE", "CHAIN", "CHAIR", "CHALK", "CHANT", "CHAOS", "CHARM", "CHART", "CHASE", "CHEAP", "CHEAT", "CHECK", "CHEEK", "CHEER", "CHESS", "CHEST", "CHIEF", "CHILD", "CHILL", "CHINA", "CHUNK", "CIVIC", "CIVIL", "CLAIM", "CLASH", "CLASS", "CLEAN", "CLEAR", "CLERK", "CLICK", "CLIFF", "CLIMB", "CLING", "CLOCK", "CLONE", "CLOSE", "CLOTH", "CLOUD", "COACH", "COAST", "COLOR", "COMET", "CORAL", "COUCH", "COULD", "COUNT", "COURT", "COVER", "CRACK", "CRAFT", "CRANE", "CRASH", "CRAWL", "CRAZE", "CRAZY", "CREAM", "CREEK", "CREEP", "CREST", "CRIME", "CRISP", "CROSS", "CROWD", "CROWN", "CRUEL", "CRUSH", "CUBIC", "CURVE", "CYCLE",
		"DAILY", "DANCE", "DATED", "DEALT", "DEATH", "DEBUT", "DECAY", "DELAY", "DELTA", "DENSE", "DEPTH", "DERBY", "DEVIL", "DIARY", "DIRTY", "DITCH", "DIZZY", "DOUBT", "DOUGH", "DRAFT", "DRAIN", "DRAMA", "DRANK", "DRAPE", "DRAWN", "DREAM", "DRESS", "DRIED", "DRIFT", "DRILL", "DRINK", "DRIVE", "DROIT", "DRONE", "DROVE", "DRUNK", "DRYER", "DWARF", "DWELL",
		"EAGER", "EAGLE", "EARTH", "EATER", "EIGHT", "ELECT", "ELITE", "EMPTY", "ENEMY", "ENJOY", "ENTER", "EQUAL", "EQUIP", "ERECT", "ERROR", "EVENT", "EVERY", "EXACT", "EXERT", "EXILE", "EXIST", "EXTRA",
		"FABLE", "FACET", "FAINT", "FAIRY", "FAITH", "FALSE", "FANCY", "FATAL", "FAULT", "FEAST", "FENCE", "FERRY", "FEVER", "FIBER", "FIELD", "FIERY", "FIFTH", "FIFTY", "FIGHT", "FINAL", "FIRST", "FLAME", "FLASH", "FLEET", "FLESH", "FLICK", "FLOAT", "FLOCK", "FLOOD", "FLOOR", "FLOUR", "FLUID", "FLUSH", "FLUTE", "FOCUS", "FORCE", "FORGE", "FORTH", "FORUM", "FOUND", "FRAME", "FRANK", "FRAUD", "FRESH", "FRONT", "FROST", "FROZE", "FRUIT", "FULLY", "FUNDS", "FUNNY", "FUZZY",
		"GIANT", "GIVEN", "GHOST", "GLARE", "GLASS", "GLEAM", "GLOBE", "GLOOM", "GLORY", "GLOSS", "GLOVE", "GOING", "GRACE", "GRADE", "GRAIN", "GRAND", "GRANT", "GRAPE", "GRAPH", "GRASP", "GRASS", "GRAVE", "GREAT", "GREEN", "GREET", "GRIEF", "GRILL", "GRIND", "GROAN", "GROOM", "GROSS", "GROUP", "GROVE", "GROWN", "GUARD", "GUESS", "GUEST", "GUIDE", "GUILT", "GUISE",
		"HABIT", "HAPPY", "HARSH", "HASTE", "HASTY", "HAUNT", "HAVEN", "HEART", "HEAVY", "HENCE", "HONOR", "HORSE", "HOTEL", "HOUSE", "HUMAN", "HUMOR", "HURRY",
		"IMAGE", "IMPLY", "INDEX", "INDIE", "INFER", "INNER", "INPUT", "IRONY", "ISSUE", "IVORY",
		"JEWEL", "JOINT", "JOKER", "JOLLY", "JUDGE", "JUICE", "JUICY",
		"KNIFE", "KNOCK", "KNACK", "KNOWN",
		"LABEL", "LABOR", "LARGE", "LASER", "LATCH", "LATER", "LAUGH", "LAYER", "LEARN", "LEASE", "LEAST", "LEAVE", "LEGAL", "LEMON", "LEVEL", "LEVER", "LIGHT", "LIMIT", "LINEN", "LIVER", "LOCAL", "LODGE", "LOGIC", "LOOSE", "LOVER", "LOWER", "LOYAL", "LUCKY", "LUNAR", "LUNCH",
		"MAGIC", "MAJOR", "MAKER", "MANOR", "MAPLE", "MARCH", "MATCH", "MAYOR", "MEDAL", "MEDIA", "MERCY", "MERGE", "MERIT", "METAL", "METER", "MIDST", "MIGHT", "MINOR", "MINUS", "MODEL", "MONEY", "MONTH", "MORAL", "MOTOR", "MOUNT", "MOUSE", "MOUTH", "MOVIE", "MUSIC", "MUDDY",
		"NAIVE", "NERVE", "NEVER", "NEWLY", "NIGHT", "NOBLE", "NOISE", "NORTH", "NOTED", "NOVEL", "NURSE",
		"OCCUR", "OCEAN", "OFFER", "OFTEN", "ONION", "ONSET", "OPERA", "ORBIT", "ORDER", "OTHER", "OUTER", "OVERT", "OWNER", "OXIDE",
		"PAINT", "PANEL", "PANIC", "PAPER", "PARTY", "PASTE", "PATCH", "PAUSE", "PEACE", "PEACH", "PEARL", "PEDAL", "PENNY", "PHASE", "PHONE", "PHOTO", "PIANO", "PIECE", "PILOT", "PINCH", "PITCH", "PIXEL", "PLACE", "PLAIN", "PLANE", "PLANT", "PLATE", "PLAZA", "PLEAD", "PLUCK", "PLUMB", "PLUME", "PLUMP", "PLUNGE", "PLUSH", "POINT", "POLAR", "POUND", "POWER", "PRESS", "PRICE", "PRIDE", "PRIME", "PRINT", "PRIOR", "PRIZE", "PROBE", "PROOF", "PROSE", "PROUD", "PROVE", "PSALM", "PULSE", "PUNCH", "PUPIL", "PURSE",
		"QUEEN", "QUEST", "QUEUE", "QUICK", "QUIET", "QUITE", "QUOTA", "QUOTE",
		"RADAR", "RALLY", "RANCH", "RANGE", "RAPID", "RATIO", "REACH", "REACT", "READY", "REALM", "REBEL", "REFER", "REIGN", "RELAX", "REPLY", "RIDER", "RIDGE", "RIFLE", "RIGHT", "RIGID", "RISKY", "RIVAL", "RIVER", "ROBIN", "ROBOT", "ROCKY", "ROUGE", "ROUGH", "ROUND", "ROUTE", "ROYAL", "RUGBY", "RURAL",
		"SAINT", "SALAD", "SAUCE", "SCALE", "SCARE", "SCENE", "SCENT", "SCOPE", "SCORE", "SCOUT", "SCRAP", "SERVE", "SETUP", "SEVEN", "SHALL", "SHAME", "SHAPE", "SHARE", "SHARK", "SHARP", "SHAVE", "SHEAR", "SHEEP", "SHEER", "SHEET", "SHELF", "SHELL", "SHIFT", "SHINE", "SHIRT", "SHOCK", "SHOOT", "SHORT", "SHOUT", "SHOVE", "SIGHT", "SILLY", "SINCE", "SIXTH", "SIXTY", "SIZED", "SKILL", "SKULL", "SLATE", "SLAVE", "SLEEP", "SLICE", "SLIDE", "SLOPE", "SMALL", "SMART", "SMELL", "SMILE", "SMOKE", "SNACK", "SNAKE", "SOLAR", "SOLID", "SOLVE", "SORRY", "SOUND", "SOUTH", "SPACE", "SPARE", "SPARK", "SPEAK", "SPEED", "SPELL", "SPEND", "SPENT", "SPICE", "SPINE", "SPLIT", "SPOKE", "SPOON", "SPORT", "SPRAY", "SQUAD", "STACK", "STAFF", "STAGE", "STAIN", "STAIR", "STAKE", "STALE", "STALK", "STALL", "STAMP", "STAND", "STARK", "START", "STATE", "STAVE", "STAYS", "STEAK", "STEAL", "STEAM", "STEEL", "STEEP", "STEER", "STERN", "STICK", "STIFF", "STILL", "STING", "STOCK", "STOLE", "STONE", "STOOD", "STOOL", "STORE", "STORM", "STORY", "STOUT", "STOVE", "STRAP", "STRAW", "STRAY", "STRIP", "STUCK", "STUDY", "STUFF", "STUMP", "STUNG", "STUNT", "STYLE", "SUGAR", "SUITE", "SUPER", "SURGE", "SWAMP", "SWEAR", "SWEAT", "SWEEP", "SWEET", "SWEPT", "SWIFT", "SWING", "SWORD", "SWORE", "SWORN",
		"TABLE", "TASTE", "TEACH", "TEETH", "TEMPO", "TENSE", "TENTH", "THEIR", "THEME", "THERE", "THESE", "THICK", "THIEF", "THING", "THINK", "THIRD", "THOSE", "THREE", "THREW", "THROW", "THUMB", "TIDAL", "TIGER", "TIGHT", "TIMER", "TIRED", "TITLE", "TODAY", "TOKEN", "TOTAL", "TOUCH", "TOUGH", "TOWER", "TOXIC", "TRACE", "TRACK", "TRADE", "TRAIL", "TRAIN", "TRAIT", "TRASH", "TREAT", "TREND", "TRIAL", "TRIBE", "TRICK", "TRIED", "TROOP", "TRUCK", "TRULY", "TRUMP", "TRUNK", "TRUST", "TRUTH", "TUMOR", "TWICE", "TWIST",
		"ULTRA", "UNCLE", "UNDER", "UNDUE", "UNION", "UNITE", "UNITY", "UNTIL", "UPPER", "UPSET", "URBAN", "USAGE", "USUAL", "UTTER",
		"VAGUE", "VALID", "VALUE", "VALVE", "VAPOR", "VAULT", "VERSE", "VIDEO", "VIGOR", "VIRAL", "VIRUS", "VISIT", "VISTA", "VITAL", "VIVID", "VOCAL", "VOICE", "VOTER",
		"WAIST", "WASTE", "WATCH", "WATER", "WEAVE", "WEIGH", "WEIRD", "WHEAT", "WHEEL", "WHERE", "WHICH", "WHILE", "WHITE", "WHOLE", "WHOSE", "WIDOW", "WIDTH", "WOMAN", "WORLD", "WORRY", "WORSE", "WORST", "WORTH", "WOULD", "WOUND", "WRATH", "WRITE", "WRONG", "WROTE",
		"YACHT", "YIELD", "YOUNG", "YOURS", "YOUTH",
		"ZONES",
		// Common 6-letter words
		"ABSORB", "ACCEPT", "ACCESS", "ACROSS", "ACTION", "ACTUAL", "AFFECT", "AFFORD", "AGENCY", "AGENDA", "ALMOST", "AMOUNT", "ANIMAL", "ANNUAL", "ANSWER", "ANYONE", "ANYWAY", "APPEAL", "APPEAR", "AROUND", "ARREST", "ARRIVE", "ARTIST", "ASPECT", "ASSERT", "ASSESS", "ASSIGN", "ASSIST", "ASSUME", "ATTACH", "ATTACK", "ATTAIN", "ATTEND", "AUGUST",
		"BASKET", "BATTLE", "BEAUTY", "BECAME", "BECOME", "BEFORE", "BEHIND", "BELONG", "BESIDE", "BEYOND", "BITTER", "BLANKET", "BORROW", "BOTTLE", "BOTTOM", "BOUNCE", "BRANCH", "BREATH", "BRIDGE", "BRIGHT", "BROKEN", "BRONZE", "BROWSE", "BUBBLE", "BUCKET", "BUDGET", "BUFFER", "BUNDLE", "BURDEN", "BUREAU", "BURGER", "BUTTER", "BUTTON", "BYPASS",
		"CAMPUS", "CANCEL", "CARBON", "CAREER", "CASTLE", "CAUGHT", "CENTER", "CHANCE", "CHANGE", "CHARGE", "CHOSEN", "CHROME", "CIRCLE", "CLAUSE", "CLIENT", "CLOSER", "COFFEE", "COLUMN", "COMBAT", "COMMON", "COMPLY", "COPPER", "CORNER", "COSTLY", "COTTON", "COUNTY", "COUPLE", "COURSE", "COVERS", "CREATE", "CREDIT", "CRISIS", "CUSTOM",
		"DAMAGE", "DANGER", "DEALER", "DEBATE", "DECADE", "DECENT", "DECIDE", "DEFEAT", "DEFEND", "DEFINE", "DEGREE", "DEMAND", "DENIAL", "DEPART", "DEPEND", "DEPLOY", "DEPICT", "DERIVE", "DESERT", "DESIGN", "DESIRE", "DETAIL", "DETECT", "DEVICE", "DEVOTE", "DIFFER", "DIGEST", "DINNER", "DIRECT", "DIVIDE", "DOCTOR", "DOLLAR", "DOMAIN", "DONATE", "DOUBLE", "DOZENS", "DRAWER", "DRIVEN", "DRIVER", "DRYING", "DURING",
		"EASILY", "EATING", "EDITOR", "EFFECT", "EFFORT", "EIGHTH", "ELEVEN", "EMERGE", "EMPIRE", "EMPLOY", "ENABLE", "ENDING", "ENERGY", "ENGAGE", "ENGINE", "ENOUGH", "ENSURE", "ENTIRE", "ENTITY", "EQUITY", "ESCAPE", "ESTATE", "EVOLVE", "EXCEED", "EXCEPT", "EXCITE", "EXCUSE", "EXEMPT", "EXPAND", "EXPECT", "EXPERT", "EXPORT", "EXPOSE", "EXTEND", "EXTENT", "FABRIC",
		"FACTOR", "FAIRLY", "FALLEN", "FAMILY", "FAMOUS", "FARMER", "FATHER", "FAULTS", "FEMALE", "FIGURE", "FILING", "FILTER", "FINALS", "FINGER", "FINISH", "FISCAL", "FLAVOR", "FLIGHT", "FLOWER", "FLYING", "FOLDER", "FOLLOW", "FORCED", "FOREST", "FORGET", "FORMAL", "FORMAT", "FORMER", "FOSSIL", "FOSTER", "FOUGHT", "FOURTH", "FREEZE", "FRIEND", "FROZEN", "FUNDED", "FUTURE",
		"GAINED", "GALAXY", "GARAGE", "GARDEN", "GATHER", "GENDER", "GENTLE", "GENTLY", "GIVING", "GLOBAL", "GOLDEN", "GOVERN", "GROWTH", "GUITAR",
		"HANDLE", "HAPPEN", "HARBOR", "HARDLY", "HAVING", "HEADER", "HEALTH", "HEAVEN", "HEIGHT", "HELMET", "HEREBY", "HIDDEN", "HIGHER", "HIGHLY", "HONEST", "HORROR", "HOUSED", "HUNGRY", "HUNTER", "HYBRID",
		"IGNORE", "IMPACT", "IMPOSE", "IMPORT", "INCOME", "INDEED", "INDOOR", "INFANT", "INFORM", "INJURY", "INLAND", "INSERT", "INSIDE", "INSIST", "INSURE", "INTACT", "INTEND", "INTENT", "INVEST", "ISLAND", "ITSELF",
		"JACKET", "JOINED", "JUNGLE", "JUNIOR", "JUSTLY",
		"KERNEL", "KICKED", "KINDLY", "KNIGHT", "KNIVES",
		"LAUNCH", "LAWYER", "LAYOUT", "LEADER", "LEAGUE", "LEGACY", "LEGEND", "LENDER", "LENGTH", "LESSON", "LETTER", "LIABLE", "LIKELY", "LINEAR", "LINKED", "LIQUID", "LISTEN", "LITTLE", "LIVELY", "LIVING", "LOCATE", "LOOKED", "LOVELY", "LOWEST", "LUXURY",
		"MAINLY", "MAKING", "MANAGE", "MANNER", "MARGIN", "MARINE", "MARKET", "MARKED", "MASTER", "MATTER", "MATURE", "MEDIUM", "MEMBER", "MEMORY", "MENTAL", "MENTOR", "MERELY", "MERGER", "METHOD", "MIDDLE", "MIGHTY", "MINING", "MINUTE", "MIRROR", "MOBILE", "MODEST", "MODIFY", "MOMENT", "MONKEY", "MONTHS", "MOSTLY", "MOTION", "MOVING", "MURDER", "MUSCLE", "MUSEUM", "MUTUAL",
		"NAMELY", "NARROW", "NATION", "NATIVE", "NATURE", "NEARBY", "NEARLY", "NEATLY", "NEEDED", "NICELY", "NOBODY", "NORMAL", "NOTING", "NOTION", "NOVICE", "NUCLEI", "NUMBER",
		"OBTAIN", "OCCUPY", "OFFEND", "OFFICE", "OFFSET", "OLDEST", "ONLINE", "OPENER", "OPENLY", "OPPOSE", "OPTION", "ORACLE", "ORANGE", "ORIENT", "ORIGIN", "OUTFIT", "OUTLET", "OUTPUT", "OXFORD",
		"PACKED", "PALACE", "PARENT", "PATROL", "PATRON", "PAYING", "PENCIL", "PEOPLE", "PERIOD", "PERMIT", "PERSON", "PHRASE", "PICKED", "PILLAR", "PILLOW", "PLANET", "PLAYER", "PLEASE", "PLEDGE", "PLENTY", "POCKET", "POETRY", "POISON", "POLICE", "POLICY", "POLITE", "POORLY", "PORTAL", "POSTER", "POTATO", "POWDER", "PRAYER", "PREFIX", "PRETTY", "PRINCE", "PRISON", "PROFIT", "PROPER", "PROVEN", "PUBLIC", "PUNISH", "PUPPET", "PURELY", "PURSUE", "PUZZLE",
		"RABBIT", "RACIAL", "RANDOM", "RARELY", "RATHER", "RATING", "READER", "REALLY", "REASON", "RECALL", "RECENT", "RECORD", "REDUCE", "REFORM", "REGAIN", "REGARD", "REGIME", "REGION", "REJECT", "RELATE", "RELIEF", "REMAIN", "REMEDY", "REMIND", "REMOTE", "REMOVE", "RENDER", "REPAIR", "REPEAT", "REPORT", "RESCUE", "RESIGN", "RESIST", "RESORT", "RESULT", "RETAIL", "RETAIN", "RETIRE", "RETURN", "REVEAL", "REVIEW", "REVOLT", "REWARD", "RIBBON", "RISING", "ROBUST", "ROCKET", "ROLLED", "ROSTER", "RULING", "RUNNER",
		"SACRED", "SAFETY", "SALARY", "SAMPLE", "SAVING", "SCHEME", "SCHOOL", "SCREEN", "SCRIPT", "SEARCH", "SEASON", "SECOND", "SECRET", "SECTOR", "SECURE", "SELECT", "SENIOR", "SERIES", "SETTLE", "SEVERE", "SHADOW", "SHAPED", "SHARED", "SHIELD", "SHOULD", "SIGNAL", "SIGNED", "SILENT", "SILVER", "SIMPLE", "SIMPLY", "SINGER", "SINGLE", "SISTER", "SLIGHT", "SLOWLY", "SMOOTH", "SOCIAL", "SOLELY", "SOLEMN", "SOUGHT", "SOURCE", "SPEECH", "SPHERE", "SPIRIT", "SPREAD", "SPRING", "SQUARE", "STABLE", "STRAIN", "STRAND", "STREAM", "STREET", "STRICT", "STRIKE", "STRING", "STRIPE", "STROKE", "STRONG", "STRUCK", "STUDIO", "SUBMIT", "SUBTLE", "SUDDEN", "SUFFER", "SUMMIT", "SUPPLY", "SURELY", "SURVEY", "SWITCH", "SYMBOL", "SYSTEM",
		"TACKLE", "TAKING", "TALENT", "TARGET", "TAUGHT", "TEMPLE", "TENANT", "TENDER", "TERROR", "THANKS", "THIRTY", "THORNY", "THOUGH", "THREAD", "THREAT", "THRIVE", "THROAT", "THRONE", "THROWN", "TICKET", "TIMBER", "TIMELY", "TISSUE", "TONGUE", "TOWARD", "TRAVEL", "TREATY", "TRIBAL", "TRICKY", "TRIPLE", "TROPHY", "TUNNEL", "TWELVE", "TWENTY", "TYCOON",
		"UNFAIR", "UNIQUE", "UNLIKE", "UNLOCK", "UNREST", "UNSTABLE", "UPDATE", "UPHOLD", "UPKEEP", "UPTURN", "URGING", "USEFUL", "UTMOST",
		"VACANT", "VALLEY", "VARIED", "VENDOR", "VESSEL", "VICTIM", "VIEWER", "VIOLET", "VIRGIN", "VIRTUE", "VISION", "VISUAL", "VOLUME",
		"WAITER", "WALKER", "WALLET", "WANDER", "WANTED", "WARMLY", "WARMTH", "WEALTH", "WEAPON", "WEEKLY", "WEIGHT", "WHOLLY", "WICKED", "WIDELY", "WILLED", "WINDOW", "WINNER", "WINTER", "WISDOM", "WITHIN", "WONDER", "WOODEN", "WORKER", "WORTHY", "WRITER",
		"YEARLY", "YELLOW",
		"ZENITH", "ZIGZAG",
		// Common 7-letter words
		"ABILITY", "ABSENCE", "ACADEMY", "ACCOUNT", "ACHIEVE", "ACQUIRE", "ADDRESS", "ADVANCE", "ADVERSE", "AFFAIRM", "ALCOHOL", "ALLEGED", "ALREADY", "AMAZING", "ANCIENT", "ANOTHER", "ANXIETY", "ANYBODY", "APPLIED", "ARRANGE", "ARRIVAL", "ARTICLE", "ASSAULT", "ATTEMPT", "ATTRACT", "AUCTION", "AVERAGE",
		"BALANCE", "BANKING", "BARGAIN", "BARRIER", "BATTERY", "BEARING", "BECAUSE", "BEDROOM", "BELIEVE", "BENEATH", "BENEFIT", "BESIDES", "BETWEEN", "BILLION", "BOMBING", "BROTHER", "BROUGHT", "BUILDER", "BURNING", "CABINET",
		"CABINET", "CABINET", "CALCIUM", "CALLING", "CAPABLE", "CAPITAL", "CAPTAIN", "CAPTURE", "CAREFUL", "CARRIED", "CATALOG", "CENTURY", "CERTAIN", "CHAMBER", "CHANNEL", "CHAPTER", "CHARITY", "CHECKED", "CHICKEN", "CHRONIC", "CIRCUIT", "CITIZEN", "CLAIMED", "CLASSIC", "CLIMATE", "CLOSING", "CLUSTER", "COASTAL", "COATING", "COLLECT", "COLLEGE", "COMMAND", "COMMENT", "COMPACT", "COMPANY", "COMPARE", "COMPEL", "COMPETE", "COMPLEX", "CONCERN", "CONDUCT", "CONFIRM", "CONFUSE", "CONNECT", "CONSENT", "CONSIST", "CONTACT", "CONTAIN", "CONTENT", "CONTEXT", "CONTROL", "CONVERT", "COOKING", "CORRECT", "COUNCIL", "COUNTRY", "COURAGE", "COVERED", "CREATED", "CREATOR", "CULTURE", "CURRENT", "CUSTOMS", "CUTTING",
		"DAMAGED", "DEALING", "DECLARE", "DECLINE", "DEFAULT", "DEFENCE", "DEFICIT", "DEFINED", "DELIVER", "DENSITY", "DEPOSIT", "DERIVED", "DESERVE", "DESPITE", "DESTINY", "DESTROY", "DEVELOP", "DEVOTED", "DIGITAL", "DIPLOMA", "DISABLE", "DISCUSS", "DISEASE", "DISMISS", "DISPLAY", "DISPOSE", "DISPUTE", "DISTANT", "DIVERSE", "DIVIDED", "DISPLAY", "DRAWING", "DRESSED", "DRINK", "DRIVING", "DROPPED", "DYNAMIC",
		"EARNEST", "EASTERN", "ECONOMY", "EDITION", "EDUCATE", "ELDERLY", "ELEMENT", "EMBRACE", "EMOTION", "EMPEROR", "ENDLESS", "ENFORCE", "ENGAGED", "ENHANCE", "ENQUIRY", "EPISODE", "EQUALLY", "EROSION", "ESSENCE", "ETERNAL", "ETHICAL", "EVIDENT", "EXACTLY", "EXAMINE", "EXAMPLE", "EXCITED", "EXECUTE", "EXHIBIT", "EXPENSE", "EXPLAIN", "EXPLOIT", "EXPLORE", "EXPRESS", "EXTREME",
		"FICTION", "FIGHTER", "FINALLY", "FINANCE", "FINDING", "FISHING", "FITNESS", "FOREIGN", "FOREVER", "FORMULA", "FORTUNE", "FORWARD", "FOUNDED", "FREEDOM", "FURTHER", "FUTURES",
		"GALLERY", "GATEWAY", "GENERAL", "GENETIC", "GENUINE", "GESTURE", "GETTING", "GLIMPSE", "GODDESS", "GRADUAL", "GRAVITY", "GREATER", "GREATLY", "GROUNDS", "GROWING", "GUARANTY", "HABITAT",
		"HALFWAY", "HANDFUL", "HEADING", "HEALTHY", "HEARING", "HELPFUL", "HELPING", "HERSELF", "HIGHWAY", "HIMSELF", "HISTORY", "HOLDING", "HOLIDAY", "HORIZON", "HOUSING", "HUNDRED", "HUNTING", "HUSBAND",
		"IMAGINE", "IMMENSE", "IMPOSED", "IMPROVE", "INCLUDE", "INDEXED", "INQUIRY", "INSPECT", "INSTALL", "INSTANT", "INTENSE", "INTERIM", "INVALID", "INVOLVE", "ISOLATE",
		"JOURNAL", "JOURNEY", "JUSTICE", "JUSTIFY",
		"KINGDOM", "KITCHEN",
		"LANDING", "LARGELY", "LASTING", "LATERAL", "LEADING", "LEARNED", "LEATHER", "LENGTHY", "LETTUCE", "LIBERAL", "LIBERTY", "LIMITED", "LINKING", "LISTING", "LITERAL", "LOGICAL", "LENGTHY", "LOOKING",
		"MACHINE", "MANAGER", "MANDATE", "MANKIND", "MANSION", "MAPPING", "MASSIVE", "MASTERY", "MEANING", "MEASURE", "MENTION", "MESSAGE", "MINIMUM", "MINERAL", "MIRACLE", "MISSILE", "MISSION", "MIXTURE", "MONITOR", "MONSTER", "MONTHLY", "MORNING", "MOUNTED", "WESTERN", "MYSTERY",
		"NATURAL", "NEITHER", "NERVOUS", "NETWORK", "NEUTRAL", "NOTABLE", "NOTHING", "NOTICED", "NUCLEAR", "NURSING", "NEUTRAL",
		"Oakland", "OBSERVE", "OBVIOUS", "OFFENSE", "OFFICER", "ONGOING", "OPENING", "OPERATE", "OPINION", "OPTIMAL", "ORGANIC", "OUTLINE", "OUTSIDE", "OVERALL", "OVERLAP",
		"PACKAGE", "PAINTER", "PARKING", "PARTIAL", "PARTNER", "PASSAGE", "PASSING", "PATIENT", "PATTERN", "PAYMENT", "PENALTY", "PENDING", "PENSION", "PERCENT", "PERFECT", "PERFORM", "PERHAPS", "PERSIST", "PHOENIX", "PICKING", "PIONEER", "PLACING", "PLANNED", "PLASTIC", "PLEASED", "POINTED", "POPULAR", "POSTING", "POVERTY", "PREDICT", "PREMIER", "PREMIUM", "PREPARE", "PRESENT", "PREVIEW", "PRIMARY", "PRINTER", "PRIVACY", "PRIVATE", "PROBLEM", "PROCEED", "PROCESS", "PRODUCE", "PRODUCT", "PROFILE", "PROGRAM", "PROJECT", "PROMISE", "PROMOTE", "PROTECT", "PROTEIN", "PROTEST", "PROVIDE", "PUBLISH", "PURPOSE", "PURSUIT", "PUSHING",
		"QUALIFY", "QUARTER", "QUICKLY", "QUIETLY",
		"RADICAL", "RAISING", "RANKING", "READING", "READILY", "REALITY", "RECEIPT", "RECEIVE", "RECOVER", "RECRUIT", "REDUCED", "REFLECT", "REFUGEE", "REGULAR", "RELATED", "RELEASE", "RELYING", "REMAINS", "REMOVAL", "RENEWAL", "REPLACE", "REPLICA", "APPLIED", "REQUEST", "REQUIRE", "RESERVE", "RESOLVE", "RESPECT", "RESPOND", "RESTORE", "RETIRED", "RETREAT", "RETURNS", "REVERSE", "REVISED", "REVIVAL", "RIVALRY", "ROUTINE", "ROYALTY", "RUNNING",
		"SATISFY", "SAVINGS", "SCANDAL", "SCATTER", "SCHOLAR", "SCORING", "SCRATCH", "SEATING", "SECURED", "SEEKING", "SEGMENT", "SEIZURE", "SELLING", "SEMINAR", "SERIOUS", "SERVING", "SESSION", "SETTING", "SETTLER", "SEVENTH", "SEVERAL", "SHELTER", "SHIFTED", "SHORTLY", "SHOWING", "SHUFFLE", "SILENCE", "SIMILAR", "SITTING", "SKILLED", "SLAVERY", "SMOKING", "SOLDIER", "SOMEONE", "SPACING", "SPECIAL", "SPECIES", "SPONSOR", "STADIUM", "STAGING", "STARING", "STARTED", "STATION", "STAYING", "STORAGE", "STRANGE", "STUDENT", "SUBJECT", "SUCCEED", "SUCCESS", "SUGGEST", "SUMMARY", "SUPPORT", "SUPREME", "SURFACE", "SURGEON", "SURPLUS", "SURVIVE", "SUSPECT", "SUSTAIN",
		"TEACHER", "TENSION", "THERAPY", "THEREBY", "THOUGHT", "TOBACCO", "TONIGHT", "TOTALLY", "TOURISM", "TOURIST", "TRADING", "TRAFFIC", "TRAGEDY", "TRAINER", "TRANSIT", "TRIBUTE", "TRIGGER", "TRIUMPH", "TROUBLE", "TURNING", "TYPICAL",
		"UNDERGO", "UNAWARE", "UNIFIED", "UNITARY", "UNKNOWN", "UNUSUAL", "UPGRADE", "URGENCY", "USUALLY", "UTILITY",
		"VACANCY", "VACCINE", "VENTURE", "VERSION", "VETERAN", "VICTORY", "VILLAGE", "VINTAGE", "VIRTUAL", "VISIBLE", "VISITOR", "VIVIDLY", "VOLCANO", "VOLTAGE", "VOLUMES",
		"WALKING", "WARNING", "WARRANT", "WASHING", "WEARING", "WEATHER", "WEBSITE", "WEDDING", "WEEKEND", "WELCOME", "WELFARE", "WHETHER", "WHISPER", "WINDING", "WINNING", "WITHDRAW", "WITHOUT", "WITNESS", "WORKING", "WORSHIP", "WRITING", "WRITTEN",
	}
}
